// include the code generated by build.rs from vmod.vcc
varnish::boilerplate!();

// our default module
mod vmod;

// the cfg macro hides the following code in non-test runs
#[cfg(test)]
mod tests {
    // add your tests here!
    varnish::vtc!(test01);
}
