// include the code generated by build.rs from vmod.vcc
// `find target -name bindings.rs` will find the relevant code, if you are curious
varnish::boilerplate!();

// our default module, implement the actual code in src/vmod.rs
mod vmod;
