[package]
name = "vmod_infiniteloop"
version = "0.0.0"
publish = false
edition.workspace = true

[build-dependencies]
varnish.workspace = true

[dependencies]
varnish.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
