lints.workspace = true

[package]
name = "vmod_infiniteloop"
version = "0.0.1"
edition = "2021"

[build-dependencies]
varnish = { path = "../.." }

[dependencies]
varnish = { path = "../.." }

[lib]
crate-type = ["cdylib"]
