[package]
name = "vmod_object"
version = "0.0.0"
publish = false
edition.workspace = true

[dependencies]
varnish.workspace = true
dashmap = "6.1.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
