[package]
name = "vmod_test"
version = "0.0.1"
edition = "2021"

[build-dependencies]
varnish = { path = ".." }

[dependencies]
varnish = { path = "..", features = ["cache_req_body"] }
varnish-sys = { path = "../varnish-sys" }

[lib]
crate-type = ["cdylib"]
