[package]
name = "vmod_test"
version = "0.0.1"
edition.workspace = true

[build-dependencies]
varnish = { path = ".." }

[dependencies]
varnish = { path = ".." }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
